reviews_path: 'data/clean_reviews.csv'
model_type: 'gpt-finetuned'
#model_type: 'gpt-lite'
#model_type: 'saiga_mistral'
#model_type: 'saiga_llama3-q2-K'
#model_type: 'saiga_llama3-q4-K'
#model_type: 'saiga_llama3-q8-0'
#model_type: 'saiga_llama3-f16'
project_dir: 'D:\Programming\Research\Thesis\paramsum'
gold_markup_path: 'data/working_dir/ready_markup.csv'
gold_markup_final_path: 'data/working_dir/crowd_markup.csv'
silver_markup_path: 'data/working_dir/${model_type}/markups/markup_T-${temperature}.csv'
silver_markup_parsed_path: 'data/working_dir/${model_type}/preprocessed_markups/markup_preprocessed_T-${temperature}.csv'
silver_markup_parsed_with_metrics_path: 'data/working_dir/${model_type}/metrics/markup_preprocessed_with_metrics_T-${temperature}.csv'
metric_file: 'data/working_dir/${model_type}/metrics/metric_file_T-${temperature}.txt'
logging_dir: 'logs/${model_type}'
temperature: 0.05

